#sudo: false

language: go

services:
  - mysql

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

build_image: drydock/u12gopls:tip
before_script:
  - mysql -e 'create database gotest;'

notifications:
 email:
   recipients:
     - "vidya@shippable.com"
   on_success: change
   on_failure: always
 irc:
   pull_requests: true
   channels:  
    - "chat.freenode.net#test-irc"
    - "chat.freenode.net#testing2"



archive: true
